sudo: required
dist: bionic
language: cpp
compiler:
  - gcc
  - clang
notifications:
  email: false
addons:
  apt:
    sources:
    packages:
    - gcc-10
    - g++-10
    - cmake
before_install:
  - sudo add-apt-repository ppa:nicola-onorata/gcc
  - sudo apt-get update
script: mkdir build && cd build && cmake ../ -DCMAKE_BUILD_TYPE=Release && make -r -j `nproc` && ./TestBSDF
