sudo: required
dist: bionic
language: cpp
compiler: gcc
notifications:
  email: false
addons:
  apt:
    sources:
    packages:
    - gcc-8
    - g++-8
    - cmake
script: mkdir build && cd build && cmake ../ && make -r -j 2
